stages:
  - test
  - build # стейдж для билда образа
  - deploy # стейдж для деплоя сервиса
check-structure-job:
  stage: test
  image: alpine:latest
  tags:
    - airflow
  script:
    - test -d dags
    - test -d spark
build-job:
  image: docker:latest # чтоб собрать докер образ, нам нужен.. докер
  stage: build
  tags:
    - airflow
  script:
    - ls -la # убедимся что раннер видит содержимое репозитория
    - docker build -t image_name . # image_name = атрибут image в docker-compose.yml
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^feature\//'
      when: never
    - when: on_success
deploy-job:
  stage: deploy
  image: tmaier/docker-compose:latest # чтоб сделать деплой через композ нам нужен.. композ
  tags:
    - airflow
  script:
    - echo "Deploying application..."
    - ls -la
    - docker-compose up -d # деплоим по-старинке
    - echo "Application successfully deployed!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - when: never
clear-job: # дополнительная джоба, которая одноразово сотрет задеплоенное
  stage: deploy
  image: tmaier/docker-compose:latest
  tags:
    - airflow
  script:
    - docker-compose rm -sf
  when: manual # только ручное выполнение (после выполнения лабораторной, например)