local.file_match "airflow_logs" {
  path_targets = [
    // по маске ищем нужные логи
    {"__path__" = "/opt/logs/dag_id=*/run_id=*/task_id=*/*.log", "job" = "airflow_logs"},
  ]
}

loki.source.file "airflow" {
  targets    = local.file_match.airflow_logs.targets
  // отправка собранных логов в дефолтный ресивер Loki
  forward_to = [loki.write.default.receiver]
}

// дефолтный ресивер Loki
loki.write "default" {
  endpoint {
    // адрес может отличаться (container_name)
    url = "http://loki:3100/loki/api/v1/push"
  }
}
